# Site settings
title: GitBucket News
#email: your-email@domain.com
description: "GitBucket is a GitHub clone powered by Scala."
baseurl: "https://gitbucket.github.io/gitbucket-news"
url: ""

# Build settings
markdown: kramdown
#permalink: prettay

paginate: 10

kramdown:
  input: GFM

gems: [jekyll-paginate]
